spring:
  application:
    name: cosmo-cats
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        '[jdbc.time_zone]': UTC
        '[jdbc.batch_size]': 15
        '[order_inserts]': true
        '[order_updates]': true
        '[query.fail_on_pagination_over_collection_fetch]': true
        '[query.in_clause_parameter_padding]': true
        '[connection.provider_disables_autocommit]': true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/cosmo_cats
    username: postgres
    password: postgres
    hikari:
      auto-commit: false
      connection-timeout: 30000
      maximum-pool-size: 10
      max-lifetime: 1800000
      pool-name: galactic-market
  liquibase:
    change-log: classpath:liquibase/changelog.yml
    enabled: true

feature:
  cosmoCats:
    enabled: true
  kittyProducts:
    enabled: false
